### ISSUE TITLE
Double clicking the tag_entry field removes listbox selection.

### ISSUE THREAD

**Issue by Nenotriple** [DevArqSangoi/das-EzBooruTagEditor#3]
When double-clicking the `tag_entry` field, the focus is moved away from the `listbox`. This clears the selection and prevents all navigation besides manually clicking an entry from the `listbox`. There may have been other ways of breaking `listbox` focus, but I never found them. Regardless, this fix should cover all circumstances.

[This is a pretty simple fix](https://stackoverflow.com/questions/10048609/how-to-keep-selections-highlighted-in-a-tkinter-listbox). We can just set the `exportselection` flag to false for the `listbox`. This prevents the `listbox` from using the primary selection, and allows it to retain its selection when a different widget gets focus.

[Line 43 reference.](https://github.com/DevArqSangoi/das-EzBooruTagEditor/blob/4ff4fb2f388bdc7e672f7116957c4b0709654c08/EzBooruTagEditor.py#L43C1-L43C1)

Simply add `exportselection=False` to the above statement like this:

`self.listbox = tk.Listbox(self.left_frame, selectmode=tk.SINGLE, yscrollcommand=scrollbar.set, exportselection=False)`

**Comment by sangoi-exe** [comment]
Thanks for this report as well, I'll check it out and implement your suggestion!

**Comment by sangoi-exe** [comment]
@Nenotriple, I implemented your suggestion, which might also solve the issue where somehow interacting with the text box to add tags, caused the app to lose the reference to the current file and cleared the interface.

**Comment by Nenotriple** [comment]
I did notice that comment and tried to reproduce the issue but never could. Fingers crossed I guess haha.
